CREATE DATABASE demo DEFAULT CHARACTER SET utf8mb4;

USE demo;

CREATE TABLE IF NOT EXISTS user(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(256) NOT NULL,
    dob DATETIME NOT NULL
)ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4;
